Repository kubevirt/web-ui, pull requests merged in 2018-10, with the labels that each got.

#38 Re-enable OKD left navigation
  frontend/public/components/nav.jsx
  frontend/public/kubevirt/components/nav.jsx
Labels: size/M

#41 Connect CreateVMWizard to network configurations
  frontend/public/kubevirt/components/vm.jsx
  frontend/public/kubevirt/models/vm.ts
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/S

#42 Upgrade kubevirt-web-ui-components to 0.1.4
  kubevirt/yarn.lock
Labels: size/XS

#43 CreateVMWizard: pass selectedNamespace prop
  frontend/public/kubevirt/components/vm.jsx
Labels: size/S

#52 README: instructions for deployment via kubevirt-ansible
  kubevirt/README.md
  kubevirt/kubevirt-web-ui.yaml
Labels: size/M

#53 mergeUpstream.sh: Merge to HEAD:master directly
  kubevirt/mergeUpstream.sh
Labels: size/S

#61 Remove semicolon which is visible in VM list
  frontend/public/kubevirt/components/vm.jsx
Labels: size/XS

#62 Add missing patternfly/react-console styles
  frontend/public/kubevirt/components/_vmconsoles.scss
Labels: size/XS

#64 Upgrade web-ui-components to 0.1.5
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/XS

#55 Use disk as boot device when booting from PXE-boot configured VM seco…
  frontend/public/kubevirt/components/modals/restart-vm-modal.jsx
  frontend/public/kubevirt/components/modals/start-stop-vm-modal.jsx
  frontend/public/kubevirt/components/vm.jsx
Labels: size/M

#65 Add Events page in VM details. Events page is watching VMI events.
  frontend/public/kubevirt/components/modals/restart-vm-modal.jsx
  frontend/public/kubevirt/components/modals/start-stop-vm-modal.jsx
  frontend/public/kubevirt/components/okdcomponents.jsx
  frontend/public/kubevirt/components/vm.jsx
Labels: size/S

#70 Remove semicolon which is visible in VM list
  frontend/public/kubevirt/components/vm.jsx
Labels: size/XS

#68 mergeUpstream.sh: increase verbosity
  kubevirt/mergeUpstream.sh
Labels: size/XS

#71 add DisksTab to CreateVmWizard
  frontend/public/kubevirt/components/vm.jsx
Labels: size/S
