Repository kubevirt/web-ui, pull requests merged in 2018-11, with the labels that each got.

#76 Upgrade web-ui-components to 0.1.6
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/XS

#72 add DisksTab to CreateVmWizard
  frontend/public/kubevirt/components/vm.jsx
Labels: size/S

#78 web-ui-v1.3: upgrade web-ui-components to 0.1.6
  kubevirt/yarn.lock
Labels: size/XS

#79 Do not show Pods with completed phase. Prefer Runnning/Pending/Failed/Unkn…
  frontend/public/kubevirt/components/utils/resources.js
Labels: size/XS

#80 Do not Pods show with completed phase. Prefer Runnning/Pending/Failed/Unkn…
  frontend/public/kubevirt/components/utils/resources.js
Labels: size/XS

#81 Re-enable monitoring and administration
  frontend/public/components/nav.jsx
  frontend/public/kubevirt/components/nav.jsx
Labels: size/S

#73 Use disk as boot device when booting from PXE-boot configured VM seco…
  frontend/public/kubevirt/components/modals/restart-vm-modal.jsx
  frontend/public/kubevirt/components/modals/start-stop-vm-modal.jsx
  frontend/public/kubevirt/components/vm.jsx
Labels: size/M

#82 v1.3: Re-enable monitoring and administration
  frontend/public/components/nav.jsx
  frontend/public/kubevirt/components/nav.jsx
Labels: size/S

#54 Add filters to VM List
  frontend/public/components/factory/list.tsx
  frontend/public/kubevirt/components/utils/resources.js
  frontend/public/kubevirt/components/vm.jsx
Labels: size/S

#83 [OKD-core] Add filters to VM List
  frontend/public/components/factory/list.tsx
  frontend/public/kubevirt/components/utils/resources.js
  frontend/public/kubevirt/components/vm.jsx
Labels: size/S

#86 Upgrade web-ui-components to 0.1.7
  kubevirt/yarn.lock
Labels: size/XS

#87 Upgrade web-ui-components to 0.1.7
  kubevirt/yarn.lock
Labels: size/XS

#88 Use :latest tag for docker image
  push.sh
Labels: size/XS

#90 Use quay.io instead of private repo
  push.sh
Labels: size/XS

#93 Read OS from VM's annotation
  frontend/public/kubevirt/components/vm.jsx
Labels: size/XS

#94 Read OS from VM's annotation
  frontend/public/kubevirt/components/vm.jsx
Labels: size/XS

#98 Upgrade web-ui-components to 0.1.7-1
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/XS

#101 Fix missing consoles
  frontend/public/kubevirt/components/vm.jsx
Labels: size/XS

#102 Fix missing consoles.v1.3
  frontend/public/kubevirt/components/vm.jsx
Labels: size/XS

#91 Add Networks and Disks to VM details
  frontend/public/kubevirt/_style.scss
  frontend/public/kubevirt/components/_disk.scss
  frontend/public/kubevirt/components/disk.jsx
  frontend/public/kubevirt/components/modals/delete-device-modal.jsx
  frontend/public/kubevirt/components/nic.jsx
  frontend/public/kubevirt/components/utils/constants.js
  frontend/public/kubevirt/components/vm.jsx
Labels: size/L

#89 consoles: add spinner when VM is starting
  frontend/public/kubevirt/components/_vmconsoles.scss
  frontend/public/kubevirt/components/modals/start-stop-vm-modal.jsx
  frontend/public/kubevirt/components/okdcomponents.jsx
  frontend/public/kubevirt/components/utils/resources.js
  frontend/public/kubevirt/components/vmconsoles.jsx
Labels: size/M

#106 Release image tags vX.Y and vX.Y.Z
  push.sh
Labels: size/XS

#105 Update @patternfly/react-console to 1.5.0
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/XL

#108 Upgrade web-ui-components to 0.1.7-2
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/XS

#99 Handle PXE boot devices order when VM is restarted.
  frontend/public/kubevirt/components/modals/delete-device-modal.jsx
  frontend/public/kubevirt/components/modals/restart-vm-modal.jsx
  frontend/public/kubevirt/components/modals/start-stop-vm-modal.jsx
Labels: size/M

#111 ResourceLauncher and refactor show CreateVMWizard
  frontend/public/kubevirt/_style.scss
  frontend/public/kubevirt/components/modals/_loader.scss
  frontend/public/kubevirt/components/modals/loader.jsx
  frontend/public/kubevirt/components/okdcomponents.jsx
  frontend/public/kubevirt/components/utils/resourceLauncher.jsx
  frontend/public/kubevirt/components/utils/showErrors.jsx
  frontend/public/kubevirt/components/utils/withResources.jsx
  frontend/public/kubevirt/components/vm.jsx
Labels: size/L

#112 fix: automatic linter fix
  frontend/public/components/factory/list.tsx
  frontend/public/kubevirt/components/disk.jsx
  frontend/public/kubevirt/components/modals/delete-device-modal.jsx
  frontend/public/kubevirt/components/modals/loader.jsx
  frontend/public/kubevirt/components/modals/restart-vm-modal.jsx
  frontend/public/kubevirt/components/modals/start-stop-vm-modal.jsx
  frontend/public/kubevirt/components/nic.jsx
  frontend/public/kubevirt/components/utils/resourceLauncher.jsx
  frontend/public/kubevirt/components/utils/resources.js
  frontend/public/kubevirt/components/utils/showErrors.jsx
  frontend/public/kubevirt/components/utils/withResources.jsx
  frontend/public/kubevirt/components/vm.jsx
  frontend/public/kubevirt/components/vmconsoles.jsx
  frontend/public/kubevirt/models/vm.ts
  frontend/public/models/index.ts
Labels: size/L

#113 Fix: rename Cog to Kebab
  frontend/public/kubevirt/components/disk.jsx
  frontend/public/kubevirt/components/nic.jsx
  frontend/public/kubevirt/components/vm.jsx
Labels: size/S

#116 add migration dialog
  frontend/public/kubevirt/components/utils/withResources.jsx
  frontend/public/kubevirt/components/vm.jsx
Labels: size/M

#117 Upgrade web-ui-components to 0.1.8
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/S

#120 [OKD-core] models: Finish co-locating kubevirt code
  frontend/public/models/index.ts
Labels: size/M

#114 [OKD-core] Add VM Template list
  frontend/public/components/app.jsx
  frontend/public/components/resource-pages.ts
  frontend/public/kubevirt/components/nav.jsx
  frontend/public/kubevirt/components/vm-template.jsx
  frontend/public/kubevirt/models/vm.ts
Labels: size/M

#121 Upgrade web-ui-components to 0.1.9
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/XS

#118 Added missing models
  frontend/public/kubevirt/models/vm.ts
Labels: size/S

#109 introduce Access consoles and Serial Console
  frontend/public/kubevirt/components/_vmconsoles.scss
  frontend/public/kubevirt/components/utils/resources.js
  frontend/public/kubevirt/components/vmconsoles.jsx
  frontend/public/kubevirt/module/okdk8s.ts
Labels: size/L

#123 Upgrade @patternfly/react-console to 1.9.1
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/XS

#124 Upgrade web-ui-components to 0.1.11
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/XS

#127 Adjust kebeb to allign with PF
  frontend/public/kubevirt/components/disk.jsx
  frontend/public/kubevirt/components/nic.jsx
  frontend/public/kubevirt/components/vm-template.jsx
  frontend/public/kubevirt/components/vm.jsx
Labels: size/XS

#128 Move remaining VM status functions to kubevirt-web-ui-components
  frontend/public/kubevirt/components/utils/resources.js
Labels: size/XS
