Repository kubevirt/web-ui, pull requests merged in 2018-12, with the labels that each got.

#135 Pass loaded VM resource to StateColumn, do not use Firehose again
  frontend/public/kubevirt/components/utils/resources.js
  frontend/public/kubevirt/components/vm.jsx
  frontend/public/kubevirt/components/vmconsoles.jsx
Labels: size/M

#131 Add Create Vm Template wizard
  frontend/public/kubevirt/components/modals/create-vm-modal.js
  frontend/public/kubevirt/components/utils/withResources.jsx
  frontend/public/kubevirt/components/vm-template.jsx
  frontend/public/kubevirt/components/vm.jsx
Labels: size/L

#138 Upgrade web-ui-components to 0.1.12
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/L

#140 Openshift cnv branding
  cmd/bridge/main.go
  frontend/public/branding.ts
  frontend/public/components/masthead.tsx
  frontend/public/imgs/openshiftvirt-logo.svg
Labels: size/L

#139 Spread out VM list columns to available space
  frontend/public/kubevirt/components/vm.jsx
Labels: size/S

#141 Adding junitReporter to generate xml report
  .gitignore
  frontend/integration-tests/protractor.conf.ts
Labels: size/XS

#144 Upgrade web-ui-components to 0.1.13
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/XS

#137 Add Disk in VM details
  frontend/public/kubevirt/components/_disk.scss
  frontend/public/kubevirt/components/disk.jsx
  frontend/public/kubevirt/components/modals/create-vm-modal.js
  frontend/public/kubevirt/components/utils/constants.js
  frontend/public/kubevirt/components/utils/modalResourceLauncher.jsx
  frontend/public/kubevirt/components/utils/withResources.jsx
  frontend/public/kubevirt/components/vm.jsx
Labels: blocked, size/L

#143 fix single object resource in WithResources
  frontend/public/kubevirt/components/utils/withResources.jsx
Labels: size/S
