Repository kubevirt/web-ui, pull requests merged in 2019-02, with the labels that each got.

#193 Allow non-admin users use web-ui
  frontend/public/components/app.jsx
  frontend/public/kubevirt/components/app.jsx
  frontend/public/kubevirt/components/modals/create-vm-modal.js
  frontend/public/kubevirt/components/utils/modalResourceLauncher.jsx
  frontend/public/kubevirt/components/utils/withResources.jsx
  frontend/public/kubevirt/components/vm-template/vm-template.jsx
Labels: size/M

#195 Fix merged junitReport duplicate declaration
  frontend/integration-tests/protractor.conf.ts
Labels: size/XS

#194 Allow non-admin users use web-ui
  frontend/public/components/app.jsx
  frontend/public/kubevirt/components/app.jsx
  frontend/public/kubevirt/components/modals/create-vm-modal.js
  frontend/public/kubevirt/components/utils/modalResourceLauncher.jsx
  frontend/public/kubevirt/components/utils/resources.js
  frontend/public/kubevirt/components/utils/withResources.jsx
  frontend/public/kubevirt/components/vm-template/vm-template.jsx
Labels: size/M

#196 Upgrade web-ui-components to 0.1.17-3
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/XS

#198 Pass dataVolumes to create vm wizard and templates list
  frontend/public/kubevirt/components/disk.jsx
  frontend/public/kubevirt/components/modals/create-vm-modal.js
  frontend/public/kubevirt/components/vm-template/vm-template.jsx
Labels: size/M

#199 add VmTemplateDetails page to VM Templates
  frontend/public/kubevirt/components/vm-template/vm-template-detail.jsx
  frontend/public/kubevirt/components/vm/vm-detail.jsx
Labels: size/M

#202 RDP connection: Get nodePort if service is NodePort type
  frontend/public/kubevirt/components/utils/resources.js
Labels: size/XS

#203 RDP connection: Get nodePort if service is NodePort type
  frontend/public/kubevirt/components/utils/resources.js
Labels: blocked, size/XS

#204 add disks/nics to vmTemplate
  frontend/public/kubevirt/components/disk.jsx
  frontend/public/kubevirt/components/modals/delete-device-modal.jsx
  frontend/public/kubevirt/components/nic.jsx
  frontend/public/kubevirt/components/vm-template/vm-template-detail.jsx
  frontend/public/kubevirt/components/vm/vm-detail.jsx
Labels: size/L

#205 Clone Dialog does not require units anymore
  frontend/public/kubevirt/components/vm/menu-actions.jsx
Labels: size/XS

#206 small fixes
  frontend/public/kubevirt/components/modals/delete-device-modal.jsx
  frontend/public/kubevirt/components/utils/withResources.jsx
Labels: size/S

#197 V2V
  frontend/public/kubevirt/_style.scss
  frontend/public/kubevirt/components/modals/create-vm-modal.js
  frontend/public/kubevirt/models/vm.ts
Labels: size/S

#209 Select custom disk size for VM using URL provision method
  frontend/integration-tests/tests/kubevirt/vm.actions.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.wizard.scenario.ts
  frontend/integration-tests/views/kubevirt/vm.view.ts
Labels: size/M
