Repository kubevirt/web-ui, pull requests merged in 2019-07, with the labels that each got.

#414 Use RWM in mocks
  frontend/integration-tests/tests/kubevirt/models/kubevirtDetailView.ts
  frontend/integration-tests/tests/kubevirt/utils/mocks.ts
  frontend/integration-tests/views/kubevirt/kubevirtDetailView.view.ts
Labels: size/M

#416 CloneDialog: support non-admin users
  frontend/public/kubevirt/components/vm/menu-actions.jsx
Labels: size/S

#417 Upgrade web-ui-components to 0.1.34-10
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/L
