Repository kubevirt/web-ui, pull requests merged in 2019-06, with the labels that each got.

#400 Upgrade web-ui-components to 0.1.34-7
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/M

#401 Fix missing negation of condition for checking VMI presence
  frontend/public/kubevirt/components/vm/menu-actions.jsx
Labels: size/XS

#404 Fix missing negation of condition for checking VMI presence
  frontend/public/kubevirt/components/vm/menu-actions.jsx
Labels: size/XS

#399 Pass vCenter secrets to create VM wizard
  frontend/public/kubevirt/components/modals/create-vm-modal.js
Labels: size/XS

#406 Pass vCenter secrets to create VM wizard
  frontend/public/kubevirt/components/modals/create-vm-modal.js
Labels: size/XS

#407 Upgrade web-ui-components to 0.1.34-8
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/S

#403 Added withResource method, fixed some inter-spec dependencies, changes for ocp4
  frontend/integration-tests/tests/kubevirt/clone.vm.scenario.ts
  frontend/integration-tests/tests/kubevirt/models/kubevirtDetailView.ts
  frontend/integration-tests/tests/kubevirt/models/template.ts
  frontend/integration-tests/tests/kubevirt/models/virtualMachine.ts
  frontend/integration-tests/tests/kubevirt/models/wizard.ts
  frontend/integration-tests/tests/kubevirt/node.maintenance.scenario.ts
  frontend/integration-tests/tests/kubevirt/template.actions.scenario.ts
  frontend/integration-tests/tests/kubevirt/template.wizard.scenario.ts
  frontend/integration-tests/tests/kubevirt/utils/consts.ts
  frontend/integration-tests/tests/kubevirt/utils/mocks.ts
  frontend/integration-tests/tests/kubevirt/utils/types.ts
  frontend/integration-tests/tests/kubevirt/utils/utils.ts
  frontend/integration-tests/tests/kubevirt/vm.actions.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.nic.binding.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.overview.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.wizard.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.yaml.scenario.ts
  frontend/integration-tests/tests/kubevirt/windows.scenario.ts
  frontend/integration-tests/views/kubevirt/virtualMachine.view.ts
Labels: size/XL

#408 Do not require VMs and filter them by activeNamespace in VM dialog
  frontend/public/kubevirt/components/modals/create-vm-modal.js
  frontend/public/kubevirt/components/utils/withResources.jsx
Labels: size/XS

#409 Do not require VMs and filter them by activeNamespace in VM dialog
  frontend/public/kubevirt/components/modals/create-vm-modal.js
  frontend/public/kubevirt/components/utils/withResources.jsx
Labels: size/XS

#411 Upgrade web-ui-components to 0.1.34-9
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/S

#397 added VMs dropdown in top consumers card
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/XS

#394 Dashboards page - infrastructure and test
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/metalkube/dashboard.scenario.ts
  frontend/integration-tests/views/metalkube/dashboards.view.ts
Labels: size/L

#405 Added TCs for VM Wizard Cloned Disk provision method
  frontend/integration-tests/tests/kubevirt/clone.vm.scenario.ts
  frontend/integration-tests/tests/kubevirt/models/virtualMachine.ts
  frontend/integration-tests/tests/kubevirt/models/wizard.ts
  frontend/integration-tests/tests/kubevirt/template.actions.scenario.ts
  frontend/integration-tests/tests/kubevirt/template.wizard.scenario.ts
  frontend/integration-tests/tests/kubevirt/utils/consts.ts
  frontend/integration-tests/tests/kubevirt/utils/mocks.ts
  frontend/integration-tests/tests/kubevirt/utils/types.ts
  frontend/integration-tests/tests/kubevirt/utils/utils.ts
  frontend/integration-tests/tests/kubevirt/vm.actions.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.overview.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.wizard.scenario.ts
  frontend/integration-tests/views/kubevirt/vm.actions.view.ts
Labels: size/L

#412 V2V: Listen on active VCenter Secret only when import provider is active
  frontend/public/kubevirt/components/modals/create-vm-modal.js
Labels: size/XS
