Repository kubevirt/web-ui, pull requests merged in 2019-03, with the labels that each got.

#212 VM Wizard refactoring and introduction of Models
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/kubevirt/mocks.ts
  frontend/integration-tests/tests/kubevirt/models/wizard.ts
  frontend/integration-tests/tests/kubevirt/utils.ts
  frontend/integration-tests/tests/kubevirt/vm.actions.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.wizard.scenario.ts
  frontend/integration-tests/views/kubevirt/vm.view.ts
  frontend/integration-tests/views/kubevirt/wizard.view.ts
Labels: size/XL

#215 Add 'Machines' section to custom kubevirt navigation
  frontend/public/kubevirt/components/nav.jsx
Labels: size/S

#219 Upgrade web-ui-components to 0.1.19
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/XS

#214 Introduce base for hosts listing page
  frontend/__tests__/features.spec.tsx
  frontend/public/components/resource-pages.ts
  frontend/public/features.ts
  frontend/public/kubevirt/components/nav.jsx
  frontend/public/metalkube/components/factory/okdfactory.tsx
  frontend/public/metalkube/components/host/host.tsx
  frontend/public/metalkube/components/host/index.tsx
  frontend/public/metalkube/components/utils/okdutils.tsx
  frontend/public/metalkube/models/host.ts
  frontend/public/metalkube/models/index.ts
  frontend/public/models/index.ts
Labels: size/L

#213 Fixed status checking to include status icon
  frontend/integration-tests/tests/kubevirt/utils.ts
  frontend/integration-tests/tests/kubevirt/vm.actions.scenario.ts
  frontend/integration-tests/views/kubevirt/vm.actions.view.ts
Labels: size/M

#216 Metalkube baremetal host detail page
  frontend/public/components/resource-pages.ts
  frontend/public/metalkube/components/host/host-detail.tsx
  frontend/public/metalkube/components/host/index.tsx
Labels: size/M

#207 Reorder boot order indexes on disk or NIC deletion
  frontend/public/kubevirt/components/modals/delete-device-modal.jsx
Labels: size/XS

#218 Metalkube host tabs
  frontend/public/metalkube/components/host/host-detail.tsx
Labels: size/M

#220 Added TC that add/remove disk/nic to running VM, added VM, VMI models
  frontend/integration-tests/tests/kubevirt/models/VirtualMachineInstance.ts
  frontend/integration-tests/tests/kubevirt/models/detailView.ts
  frontend/integration-tests/tests/kubevirt/models/virtualMachine.ts
  frontend/integration-tests/tests/kubevirt/utils.ts
  frontend/integration-tests/tests/kubevirt/vm.actions.scenario.ts
  frontend/integration-tests/views/crud.view.ts
  frontend/integration-tests/views/kubevirt/virtualMachine.view.ts
  frontend/integration-tests/views/kubevirt/virtualMachineInstance.view.ts
Labels: size/L

#223 Add baremetal host events to detail page
  frontend/public/metalkube/components/host/host-detail.tsx
Labels: size/S

#221 [OKD-Core] Add Cluster Overview
  frontend/public/components/app.jsx
  frontend/public/components/events.jsx
  frontend/public/kubevirt/_style.scss
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
  frontend/public/kubevirt/components/cluster/events-inner-overview.jsx
  frontend/public/kubevirt/components/nav.jsx
Labels: blocked, size/L

#226 Add InfrastructureModel
  frontend/public/kubevirt/models/vm.ts
Labels: size/S

#227 return Migration to the menu
  frontend/public/kubevirt/components/vm/menu-actions.jsx
Labels: size/XS

#225 Create VM templates list page via resource pages
  frontend/public/components/app.jsx
  frontend/public/components/resource-pages.ts
  frontend/public/kubevirt/models/vm.ts
Labels: size/XS

#228 Refactor to use ClusterOverviewContext
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
Labels: blocked, size/M

#230 Upgrade web-ui-components to 0.1.20
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/M

#232 Upgrade web-ui-components to 0.1.21
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/M

#229 Fetch Overview Details Card data
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
Labels: size/M

#224 vmStatus refactoring
  frontend/public/components/factory/list.tsx
  frontend/public/kubevirt/components/utils/resources.js
  frontend/public/kubevirt/components/vm/menu-actions.jsx
  frontend/public/kubevirt/components/vm/vm.jsx
Labels: size/S

#233 Created environment for storage dashboard view
  frontend/public/components/app.jsx
  frontend/public/imgs/storage-dashboard.jpg
  frontend/public/kubevirt/components/nav.jsx
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/S

#236 Updated the ocs/storage dashboard mockup
  frontend/public/imgs/ocs-dashboard.png
  frontend/public/imgs/storage-dashboard.jpg
  frontend/public/storage/_style.scss
  frontend/public/storage/components/storage-overview/storage-overview.jsx
  frontend/public/storage/components/storage-overview/storage-overview.scss
  frontend/public/style.scss
Labels: size/XS

#235 Capacity: use real data in ClusterOverview
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
Labels: size/M

#238 Upgrade web-ui-components to 0.1.22
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/M

#241 [OKD-Core] Add namespace prop to EventStream and fix scrolling
  frontend/public/components/events.jsx
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
  frontend/public/kubevirt/components/cluster/events-inner-overview.jsx
Labels: size/XS

#244 Prometheus polling5s
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
Labels: size/XS

#246 remove buggy migration actions from overview
  frontend/public/kubevirt/components/vm/menu-actions.jsx
Labels: size/XS

#234 Add Clone VM test cases
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/kubevirt/clone.vm.scenario.ts
  frontend/integration-tests/tests/kubevirt/kubevirt.login.scenario.ts
  frontend/integration-tests/tests/kubevirt/mocks.ts
  frontend/integration-tests/tests/kubevirt/models/detailView.ts
  frontend/integration-tests/tests/kubevirt/models/virtualMachine.ts
  frontend/integration-tests/tests/kubevirt/models/virtualMachineInstance.ts
  frontend/integration-tests/tests/kubevirt/models/wizard.ts
  frontend/integration-tests/tests/kubevirt/template.wizard.scenario.ts
  frontend/integration-tests/tests/kubevirt/utils.ts
  frontend/integration-tests/tests/kubevirt/vm.actions.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.wizard.scenario.ts
  frontend/integration-tests/views/kubevirt/virtualMachine.view.ts
  frontend/integration-tests/views/kubevirt/virtualMachineInstance.view.ts
  frontend/integration-tests/views/kubevirt/vm.actions.view.ts
  frontend/integration-tests/views/kubevirt/wizard.view.ts
Labels: size/XL

#242 change API of isMigrating and VmStatus/VmDetail so it is easier for consumption
  frontend/public/components/overview/index.tsx
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
  frontend/public/kubevirt/components/utils/constants.js
  frontend/public/kubevirt/components/utils/resources.js
  frontend/public/kubevirt/components/vm/menu-actions.jsx
  frontend/public/kubevirt/components/vm/vm-detail.jsx
  frontend/public/kubevirt/components/vm/vm.jsx
  frontend/public/kubevirt/components/vmconsoles.jsx
Labels: size/L
