Repository kubevirt/web-ui, pull requests merged in 2019-04, with the labels that each got.

#250 Sync navigation structure with 'upstream'
  frontend/public/kubevirt/components/nav.jsx
Labels: size/S

#251 Add breadcrumbs to the baremetal host detail page
  frontend/public/metalkube/components/host/host-detail.tsx
Labels: size/XS

#249 Add create baremetal host dialog
  frontend/public/metalkube/components/host/host.tsx
  frontend/public/metalkube/components/modals/create-host-modal.tsx
Labels: size/M

#248 Add binding type to NICs
  frontend/public/kubevirt/components/nic.jsx
Labels: size/S

#237 Disable restart action in VM import status
  frontend/public/kubevirt/components/vm/menu-actions.jsx
  frontend/public/kubevirt/components/vm/vm-detail.jsx
  frontend/public/kubevirt/components/vm/vm.jsx
Labels: size/L

#252 Upgrade web-ui-components to 0.1.23
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/S

#255 Pass services to vm details
  frontend/public/kubevirt/components/vm/vm-detail.jsx
Labels: size/XS

#254 Capacity card refactored
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
Labels: size/M

#256 Fix failing tests on cluster-overview
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
Labels: size/XS

#243 Check if data exists first on host detail page
  frontend/public/metalkube/components/host/host-detail.tsx
  frontend/public/metalkube/components/utils/selectors.tsx
Labels: size/M

#231 add test for creating vm from yaml
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/kubevirt/mocks.ts
  frontend/integration-tests/tests/kubevirt/models/yaml.ts
  frontend/integration-tests/tests/kubevirt/utils.ts
  frontend/integration-tests/tests/kubevirt/vm.yaml.scenario.ts
Labels: size/L

#258 Avoid copy&paste in getting prometheus base URL
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
Labels: size/XS

#257 Connect ClusterOverview Utilization card to real data
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
Labels: blocked, size/S

#261 Add baremetal hosts to cluster overview resources
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
Labels: size/XS

#259 ClusterOverview: Add Memory to Utilization
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
Labels: size/XS

#263 ClusterOverview: Improve prometheus query for CPU Capacity
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
Labels: size/XS

#264 ClusterOverview: Merge CPU/mem Capacity and Utilization stats
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
Labels: size/XS

#266 Upgrade web-ui-components to 0.1.24
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/S

#260 Details, Inventory card and Health card for Storage Dashboard
  frontend/public/models/index.ts
  frontend/public/storage/_style.scss
  frontend/public/storage/components/storage-overview/storage-overview.jsx
  frontend/public/storage/components/storage-overview/storage-overview.scss
  frontend/public/storage/models/storage.ts
  frontend/public/style.scss
Labels: size/L

#265 Filter NAD by namespace when creating new nic raw
  frontend/public/kubevirt/components/nic.jsx
Labels: size/S

#240 Connect TopConsumers to prometheus
  frontend/public/components/app.jsx
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
Labels: blocked, size/M

#268 Remove Namespace column from hosts listing
  frontend/public/metalkube/components/host/host.tsx
Labels: size/M

#267 Add dashhboard page and move all dashboards there
  frontend/public/components/app.jsx
  frontend/public/kubevirt/components/dashboards/dashboards.jsx
  frontend/public/kubevirt/components/nav.jsx
Labels: size/M

#273 Capacity card integration
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/S

#272 Added disks to inventory
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/S

#275 Added Events card
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/XS

#287 Fix undefined namespace when NIC called from VmTemplateDetails
  frontend/public/kubevirt/components/nic.jsx
Labels: size/XS

#289 Fix styles for modal dialogs
  frontend/public/kubevirt/components/modals/cancel-vmi-migration-modal.jsx
  frontend/public/kubevirt/components/modals/restart-vm-modal.jsx
  frontend/public/kubevirt/components/modals/start-stop-vm-modal.jsx
Labels: size/XS

#281 Integrated performance/Utilzation card
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/S

#291 Do not fail in project status when there are no VMs
  frontend/public/components/overview/index.tsx
Labels: size/XS

#283 Introduce LazyRenderer component
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
  frontend/public/kubevirt/components/utils/lazyRenderer.jsx
Labels: size/M

#292 Upgrade web-ui-components to 0.1.26
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/XS

#296 Added lazyRenderer for storage overview
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/XS

#270 Utilization: Add Disk Usage chart
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
Labels: size/M

#286 Use simple format of timestamp for cluster events
  frontend/public/kubevirt/components/cluster/events-inner-overview.jsx
Labels: size/XS

#280 Fetch alerts for cluster dashboard
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
Labels: size/S

#293 Use diferent nameing schema for status group than single status
  frontend/public/kubevirt/components/vm/vm.jsx
Labels: size/XS

#290 Start using BaremetalHostStatus component for host status cell
  frontend/public/metalkube/components/host/host.tsx
Labels: size/S

#299 Integrated alerts card for storage dashboard
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/S

#282 Rename cnv.io labels to kubevirt.io
  frontend/integration-tests/tests/kubevirt/clone.vm.scenario.ts
  frontend/integration-tests/tests/kubevirt/mocks.ts
  frontend/public/kubevirt/components/utils/resources.js
Labels: size/M

#253 Update machine cell in hosts listing
  frontend/public/metalkube/components/host/MachineLink.jsx
  frontend/public/metalkube/components/host/host.tsx
  frontend/public/metalkube/components/host/machine-cell.jsx
  frontend/public/metalkube/components/utils/constants.js
Labels: size/M

#297 add nic binding and fix adding nic failure
  frontend/integration-tests/tests/kubevirt/clone.vm.scenario.ts
  frontend/integration-tests/tests/kubevirt/mocks.ts
  frontend/integration-tests/tests/kubevirt/models/virtualMachine.ts
  frontend/integration-tests/tests/kubevirt/models/wizard.ts
  frontend/integration-tests/tests/kubevirt/template.wizard.scenario.ts
  frontend/integration-tests/tests/kubevirt/utils.ts
  frontend/integration-tests/tests/kubevirt/vm.actions.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.wizard.scenario.ts
  frontend/integration-tests/views/kubevirt/virtualMachine.view.ts
Labels: size/S

#300 Added filter to events for storage dashboard
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/XS

#274 Add Role cell to hosts listing
  frontend/public/metalkube/components/host/host.tsx
Labels: size/M

#302 [OKD-Core] fix (HACK) frequent v1.quota.openshift.io APIService updates
  frontend/public/module/k8s/k8s-actions.ts
Labels: size/XS

#303 Revert "[OKD-Core] fix (HACK) frequent v1.quota.openshift.io APIService updates"
  frontend/public/module/k8s/k8s-actions.ts
Labels: size/XS

#298 Integrated top consumer card for storage dashboard
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/S

#276 added data resiliency integration
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/M

#278 Add test for vm overview page
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/kubevirt/clone.vm.scenario.ts
  frontend/integration-tests/tests/kubevirt/mocks.ts
  frontend/integration-tests/tests/kubevirt/models/detailView.ts
  frontend/integration-tests/tests/kubevirt/utils.ts
  frontend/integration-tests/tests/kubevirt/vm.overview.scenario.ts
  frontend/integration-tests/views/kubevirt/virtualMachine.view.ts
Labels: size/L

#304 Upgrade web-ui-components to 0.1.27
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/S

#301 Add 'Start Maintenance' action to Host
  frontend/public/metalkube/components/host/host.tsx
  frontend/public/metalkube/components/host/menu-actions.ts
  frontend/public/metalkube/components/modals/start-maintenance-modal.jsx
Labels: size/L

#294 Add disk stats to cluster overview dashboard
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/M

#306 Modified latency query, added recovery rate query in performance card
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/XS

#307 fix storage unused var
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/XS

#310 fix setCephDiskStats()
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
Labels: size/XS

#311 Streamline fetching data for dashboards
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
Labels: size/L

#284 Utilization: disk IO RW
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
Labels: size/XS

#308 Provide machine and nodes resources to BaremetalHostStatus
  frontend/public/metalkube/components/host/host.tsx
Labels: size/XS

#313 Upgrade web-ui-components to 0.1.28
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/L

#314 using the recording rule for showing the latency in utilization card
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/XS

#288 finalize vmware v2v: update status API
  frontend/public/kubevirt/components/vm/menu-actions.jsx
  frontend/public/kubevirt/components/vm/vm-detail.jsx
  frontend/public/kubevirt/components/vm/vm.jsx
Labels: size/S

#315 Upgrade web-ui-components to 0.1.29
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/XS

#312 Fetch Health for kubevirt and cepth
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: blocked, size/M

#317 Fix ResourceKebab disapearing
  frontend/public/components/utils/kebab.tsx
Labels: size/M

#318 Upgrade web-ui-components to 0.1.30
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/S

#319 Changed the top consumer query
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/XS

#320 [OKD-CORE] Hotfix for missing node-machine relation
  frontend/public/components/node.tsx
Labels: size/XS

#321 Do not override existing health data
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/XS

#322 Fix host detail when hardware info is not available
  frontend/public/metalkube/components/host/host-detail.tsx
  frontend/public/metalkube/components/utils/selectors.tsx
Labels: size/L

#324 Upgrade web-ui-components to 0.1.32
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/S

#325 Changes in interval timer
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/S

#327 Upgrade web-ui-components to 0.1.33
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/M

#295 Add L2 RDP test case
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/kubevirt/clone.vm.scenario.ts
  frontend/integration-tests/tests/kubevirt/kubevirt.login.scenario.ts
  frontend/integration-tests/tests/kubevirt/mocks.ts
  frontend/integration-tests/tests/kubevirt/models/virtualMachine.ts
  frontend/integration-tests/tests/kubevirt/models/wizard.ts
  frontend/integration-tests/tests/kubevirt/template.wizard.scenario.ts
  frontend/integration-tests/tests/kubevirt/utils.ts
  frontend/integration-tests/tests/kubevirt/vm.wizard.scenario.ts
  frontend/integration-tests/tests/kubevirt/windows.scenario.ts
  frontend/integration-tests/views/kubevirt/virtualMachine.view.ts
  frontend/integration-tests/views/kubevirt/vm.actions.view.ts
  frontend/integration-tests/views/kubevirt/wizard.view.ts
Labels: size/L

#331 Bug fixes
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/S

#332 Bug fixes
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/S

#328 [OKD-Core] Add Node maintenance action
  frontend/public/components/node.tsx
  frontend/public/kubevirt/components/node/node-maintenance-modal.jsx
  frontend/public/kubevirt/components/node/node.jsx
  frontend/public/kubevirt/models/vm.ts
Labels: size/L

#329 Do not show silenced and inhibited alerts
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/XS

#330 Do not show silenced and inhibited alerts
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/XS

#334 Upgrade web-ui-components to 0.1.33-1
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/S

#335 Metalkube renamed to Metal3
  frontend/public/metalkube/models/host.ts
Labels: size/XS

#336 Metalkube renamed to Metal3
  frontend/public/metalkube/models/host.ts
Labels: size/XS

#337 Add test cases for live migration
  frontend/integration-tests/tests/kubevirt/models/virtualMachine.ts
  frontend/integration-tests/tests/kubevirt/utils.ts
  frontend/integration-tests/tests/kubevirt/vm.actions.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.wizard.scenario.ts
  frontend/integration-tests/views/crud.view.ts
  frontend/integration-tests/views/kubevirt/virtualMachine.view.ts
  frontend/integration-tests/views/kubevirt/vm.actions.view.ts
Labels: size/L

#340 Revert "Metalkube renamed to Metal3"
  frontend/public/metalkube/models/host.ts
Labels: size/XS

#339 [OKD-Core] Use NodeStatus from web-ui-components
  frontend/public/components/node.tsx
  frontend/public/kubevirt/components/node/node-maintenance-modal.jsx
  frontend/public/kubevirt/components/node/node.jsx
Labels: size/M

#341 Remove nav link to dashboard
  frontend/public/kubevirt/components/nav.jsx
Labels: size/XS

#342 Upgrade web-ui-components to 0.1.34
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/S

#344 [okd-core] Default SERVER_FLAGS.registry
  frontend/public/components/app.jsx
  frontend/public/kubevirt/components/init.js
Labels: size/M

#346 [okd-core] Pass v2v custom params from ConfigMap to SERVER_FLAGS
  cmd/bridge/config.go
  cmd/bridge/main.go
  frontend/public/components/app.jsx
  frontend/public/kubevirt/components/init.js
  server/server.go
Labels: size/M

#347 [OKD-Core] Do not add maintenance actions if NodeMaintenance CRD is m…
  frontend/public/components/node.tsx
  frontend/public/kubevirt/components/node/node.jsx
Labels: size/M

#348 Backport [okd-core] Pass v2v custom params from ConfigMap to SERVER_FLAGS
  cmd/bridge/config.go
  cmd/bridge/main.go
  frontend/public/kubevirt/components/init.js
  server/server.go
Labels: size/M

#349 [OKD-Core] Do not add maintenance actions if NodeMaintenance CRD is m…
  frontend/public/components/node.tsx
  frontend/public/kubevirt/components/node/node.jsx
Labels: size/M

#350 Upgrade web-ui-components to 0.1.34-1
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/S
