Repository kubevirt/web-ui, pull requests merged in 2019-01, with the labels that each got.

#152 [OKD] automatic eslint fix
  frontend/public/components/nav.jsx
  frontend/public/kubevirt/components/nav.jsx
Labels: size/S

#151 update PropTypes
  frontend/public/kubevirt/components/utils/withResources.jsx
Labels: size/XS

#153 Use WithResources for fetching resources for VmDetails
  frontend/public/kubevirt/components/vm.jsx
Labels: size/M

#157 Pass k8sGet, k8sPatch and Loading component to vm details
  frontend/public/kubevirt/components/vm/vm.jsx
Labels: size/XS

#129 Add DesktopViewer among other consoles
  frontend/public/kubevirt/components/utils/resources.js
  frontend/public/kubevirt/components/vmconsoles.jsx
Labels: blocked, size/L

#158 Generate tests for all vm provision methods based on original smoke test
  frontend/integration-tests/tests/kubevirt/vm.wizard.scenario.ts
  frontend/integration-tests/views/kubevirt/vm.view.ts
Labels: size/L

#164 Upgrade web-ui-components to 0.1.15
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/S

#166 Show full OS name in templates view
  frontend/public/kubevirt/components/vm-template/vm-template.jsx
Labels: size/M

#168 Pass function to setState when changing NIC
  frontend/public/kubevirt/components/nic.jsx
Labels: size/S

#165 pass importer pods to VmStatus and VmDetail
  frontend/public/kubevirt/components/utils/constants.js
  frontend/public/kubevirt/components/utils/modalResourceLauncher.jsx
  frontend/public/kubevirt/components/utils/resources.js
  frontend/public/kubevirt/components/utils/withResources.jsx
  frontend/public/kubevirt/components/vm/vm-detail.jsx
  frontend/public/kubevirt/components/vm/vm.jsx
Labels: size/L

#169 Load list of vmi migrations. Fix util methods for finding vm migration
  frontend/public/kubevirt/components/utils/resources.js
  frontend/public/kubevirt/components/vm/vm-detail.jsx
  frontend/public/kubevirt/components/vm/vm.jsx
Labels: size/S

#171 fix migration + refactoring
  frontend/public/kubevirt/components/disk.jsx
  frontend/public/kubevirt/components/modals/create-vm-modal.js
  frontend/public/kubevirt/components/nic.jsx
  frontend/public/kubevirt/components/utils/resources.js
  frontend/public/kubevirt/components/vm/menu-actions.jsx
  frontend/public/kubevirt/components/vm/vm-detail.jsx
  frontend/public/kubevirt/components/vm/vm.jsx
  frontend/public/kubevirt/components/vmconsoles.jsx
Labels: size/M

#170 [OKD-core] Show VM, VMI, Migrations and various vm pod events in VM e…
  frontend/public/components/events.jsx
  frontend/public/kubevirt/components/vm/vm-detail.jsx
Labels: size/M

#172 volumeName from disk spec is removed. apiVersion changed to v1alpha3.
  frontend/public/kubevirt/components/disk.jsx
  frontend/public/kubevirt/components/modals/delete-device-modal.jsx
  frontend/public/kubevirt/components/utils/resources.js
  frontend/public/kubevirt/models/vm.ts
Labels: size/S

#176 Hide VM migration menu items.
  frontend/public/kubevirt/components/vm/menu-actions.jsx
Labels: size/XS

#175 Fix default redirect if KUBEVIRT flag is missing
  frontend/public/kubevirt/components/app.jsx
Labels: size/XS

#178 Upgrade web-ui-components to 0.1.16
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/XS

#163 Added tests for vm list/detail vm view actions (start, stop, restart, delete)
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/kubevirt/mocks.ts
  frontend/integration-tests/tests/kubevirt/utils.ts
  frontend/integration-tests/tests/kubevirt/vm.actions.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.wizard.scenario.ts
  frontend/integration-tests/views/crud.view.ts
  frontend/integration-tests/views/kubevirt/vm.actions.view.ts
Labels: size/L

#183 Use uniqe prop for resource in WithResource component.
  frontend/public/kubevirt/components/utils/withResources.jsx
  frontend/public/kubevirt/components/vm/vm-detail.jsx
Labels: size/S

#179 Lower logo font size
  frontend/public/imgs/okdvirt-logo.svg
  frontend/public/imgs/openshiftvirt-logo.svg
Labels: size/XS

#184 [OKD-core] Add YAML template for VirtualMachineModel
  frontend/public/kubevirt/models/vm-yaml-templates.ts
  frontend/public/models/yaml-templates.ts
Labels: size/M

#185 README: adjust for KubeVirt context
  README.md
Labels: size/S

#186 Upgrade web-ui-components to 0.1.17-1
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/XS

#188 Add Clone VM Dialog
  frontend/public/kubevirt/components/utils/modalResourceLauncher.jsx
  frontend/public/kubevirt/components/vm/menu-actions.jsx
Labels: size/M

#187 README: add video walk-through
  README.md
Labels: size/XS

#190 Refactor: move getResource() to web-ui-components
  frontend/public/kubevirt/components/disk.jsx
  frontend/public/kubevirt/components/modals/create-vm-modal.js
  frontend/public/kubevirt/components/nic.jsx
  frontend/public/kubevirt/components/utils/resources.js
  frontend/public/kubevirt/components/vm/menu-actions.jsx
  frontend/public/kubevirt/components/vm/vm-detail.jsx
  frontend/public/kubevirt/components/vm/vm.jsx
  frontend/public/kubevirt/components/vmconsoles.jsx
Labels: size/M

#191 Upgrade web-ui-components to 0.1.18
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/XS

#192 Upgrade web-ui-components to 0.1.17-2
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/XS

#189 Updated css selectors for vm actions tests
  frontend/integration-tests/views/kubevirt/vm.actions.view.ts
Labels: size/XS
