Repository kubevirt/web-ui, pull requests merged in 2019-05, with the labels that each got.

#345 Add dashboard to navigation
  frontend/public/kubevirt/components/nav.jsx
Labels: size/XS

#355 [OKD-Core] Check namespace before deleting it
  frontend/integration-tests/protractor.conf.ts
Labels: size/XS

#356 Upgrade web-ui-components to 0.1.33-2
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/S

#351 Add storage and network top consumers
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
Labels: size/S

#357 Add stop maintenance modal
  frontend/public/kubevirt/components/node/node.jsx
  frontend/public/kubevirt/components/node/stop-maintenance-modal.jsx
Labels: size/M

#359 Upgrade web-ui-components to 0.1.34-2
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/S

#343 Add Node maintenance test cases
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/kubevirt/clone.vm.scenario.ts
  frontend/integration-tests/tests/kubevirt/kubevirt.login.scenario.ts
  frontend/integration-tests/tests/kubevirt/mocks.ts
  frontend/integration-tests/tests/kubevirt/models/detailView.ts
  frontend/integration-tests/tests/kubevirt/models/pod.ts
  frontend/integration-tests/tests/kubevirt/models/virtualMachine.ts
  frontend/integration-tests/tests/kubevirt/models/wizard.ts
  frontend/integration-tests/tests/kubevirt/node.maintenance.scenario.ts
  frontend/integration-tests/tests/kubevirt/template.wizard.scenario.ts
  frontend/integration-tests/tests/kubevirt/utils/consts.ts
  frontend/integration-tests/tests/kubevirt/utils/utils.ts
  frontend/integration-tests/tests/kubevirt/vm.actions.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.overview.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.wizard.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.yaml.scenario.ts
  frontend/integration-tests/tests/kubevirt/windows.scenario.ts
  frontend/integration-tests/views/kubevirt/node.view.ts
  frontend/integration-tests/views/kubevirt/pod.view.ts
  frontend/integration-tests/views/kubevirt/virtualMachine.view.ts
  frontend/integration-tests/views/kubevirt/wizard.view.ts
Labels: size/L

#360 Update new VM from yaml link to ~new
  frontend/public/kubevirt/components/vm/vm.jsx
Labels: size/XS

#362 Add safe click method, fix classes in VM Detail, refacactoring
  frontend/integration-tests/tests/kubevirt/mocks.ts
  frontend/integration-tests/tests/kubevirt/models/virtualMachine.ts
  frontend/integration-tests/tests/kubevirt/models/wizard.ts
  frontend/integration-tests/tests/kubevirt/models/yaml.ts
  frontend/integration-tests/tests/kubevirt/utils/utils.ts
  frontend/integration-tests/tests/kubevirt/vm.actions.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.overview.scenario.ts
  frontend/integration-tests/views/crud.view.ts
  frontend/integration-tests/views/kubevirt/virtualMachine.view.ts
Labels: size/L

#363 [BACKPORT] Update new VM from yaml link to ~new
  frontend/public/kubevirt/components/vm/vm.jsx
Labels: size/XS

#326 add test for nic binding
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/kubevirt/mocks.ts
  frontend/integration-tests/tests/kubevirt/models/detailView.ts
  frontend/integration-tests/tests/kubevirt/utils/utils.ts
  frontend/integration-tests/tests/kubevirt/vm.nic.binding.scenario.ts
  frontend/integration-tests/views/kubevirt/virtualMachine.view.ts
  frontend/integration-tests/views/kubevirt/wizard.view.ts
Labels: size/L

#365 Add stop maintenance modal
  frontend/public/kubevirt/components/node/node.jsx
  frontend/public/kubevirt/components/node/stop-maintenance-modal.jsx
Labels: size/M

#366 Upgrade web-ui-components to 0.1.34-3
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/S

#364 Display correct migration options in kebab
  frontend/public/kubevirt/components/vm/vm.jsx
Labels: size/XS

#358 Time Axis - Utilization Card (Storage Overview)
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/XS

#367 Pass virtual machines list to create VM wizard
  frontend/public/kubevirt/components/modals/create-vm-modal.js
Labels: size/XS

#369 fix #368
  frontend/public/kubevirt/components/utils/withResources.jsx
Labels: size/S

#372 Display correct migration options in kebab
  frontend/public/kubevirt/components/vm/vm.jsx
Labels: size/XS

#371 Pass virtual machines list to create VM wizard
  frontend/public/kubevirt/components/modals/create-vm-modal.js
Labels: size/XS

#361 Extract common dashboard functionality
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
  frontend/public/kubevirt/components/dashboards/index.js
  frontend/public/kubevirt/components/dashboards/utils.js
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/L

#373 fix #368
  frontend/public/kubevirt/components/utils/withResources.jsx
Labels: size/S

#354 show warn and do not fetch unnecesary data when prometheus/alertmanager base url is not available
  frontend/public/kubevirt/components/cluster/cluster-overview.jsx
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/L

#370 Added few more prometheus queries for top consumer card
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/S

#375 Disable Restart and Migrate menu items when there is no VMI
  frontend/public/kubevirt/components/vm/menu-actions.jsx
Labels: size/S

#380 Disable Restart and Migrate menu items when there is no VMI
  frontend/public/kubevirt/components/vm/menu-actions.jsx
Labels: size/S

#384 Fix syntax
  cmd/bridge/main.go
Labels: size/XS

#374 Add test for project overview
  frontend/integration-tests/tests/kubevirt/kubevirt.login.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.overview.scenario.ts
  frontend/integration-tests/views/horizontal-nav.view.ts
  frontend/integration-tests/views/kubevirt/project.view.ts
  frontend/integration-tests/views/kubevirt/vm.actions.view.ts
Labels: size/L

#386 Protect form missing actionArgs
  frontend/public/kubevirt/components/vm/menu-actions.jsx
Labels: size/XS

#387 Upgrade web-ui-components to 0.1.34-6
  kubevirt/package.json
  kubevirt/yarn.lock
Labels: size/S

#378 Add template test cases for adding nics/disks, refactored Wizard
  frontend/integration-tests/protractor.conf.ts
  frontend/integration-tests/tests/kubevirt/clone.vm.scenario.ts
  frontend/integration-tests/tests/kubevirt/kubevirt.login.scenario.ts
  frontend/integration-tests/tests/kubevirt/mocks.ts
  frontend/integration-tests/tests/kubevirt/models/detailView.ts
  frontend/integration-tests/tests/kubevirt/models/kubevirtDetailView.ts
  frontend/integration-tests/tests/kubevirt/models/pod.ts
  frontend/integration-tests/tests/kubevirt/models/template.ts
  frontend/integration-tests/tests/kubevirt/models/virtualMachine.ts
  frontend/integration-tests/tests/kubevirt/models/wizard.ts
  frontend/integration-tests/tests/kubevirt/node.maintenance.scenario.ts
  frontend/integration-tests/tests/kubevirt/template.actions.scenario.ts
  frontend/integration-tests/tests/kubevirt/template.wizard.scenario.ts
  frontend/integration-tests/tests/kubevirt/utils/consts.ts
  frontend/integration-tests/tests/kubevirt/utils/utils.ts
  frontend/integration-tests/tests/kubevirt/vm.actions.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.nic.binding.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.overview.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.wizard.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.yaml.scenario.ts
  frontend/integration-tests/tests/kubevirt/windows.scenario.ts
  frontend/integration-tests/views/kubevirt/kubevirtDetailView.view.ts
  frontend/integration-tests/views/kubevirt/virtualMachine.view.ts
  frontend/integration-tests/views/kubevirt/wizard.view.ts
Labels: size/XXL

#377 Add missing actions props to overview header
  frontend/public/kubevirt/components/overview/vm-overview.jsx
Labels: size/M

#391 Add empty check for VMI object
  frontend/public/kubevirt/components/vm/menu-actions.jsx
Labels: size/XS

#392 Add empty check for VMI object
  frontend/public/kubevirt/components/vm/menu-actions.jsx
Labels: size/XS

#389 Add test case for adding already added net-attach-def
  frontend/integration-tests/tests/kubevirt/clone.vm.scenario.ts
  frontend/integration-tests/tests/kubevirt/models/kubevirtDetailView.ts
  frontend/integration-tests/tests/kubevirt/models/template.ts
  frontend/integration-tests/tests/kubevirt/models/virtualMachine.ts
  frontend/integration-tests/tests/kubevirt/models/wizard.ts
  frontend/integration-tests/tests/kubevirt/template.actions.scenario.ts
  frontend/integration-tests/tests/kubevirt/utils/utils.ts
  frontend/integration-tests/tests/kubevirt/vm.actions.scenario.ts
Labels: size/M

#396 Add TC to check DV is cloned when VM is created from template
  frontend/integration-tests/tests/kubevirt/clone.vm.scenario.ts
  frontend/integration-tests/tests/kubevirt/mocks.ts
  frontend/integration-tests/tests/kubevirt/models/detailView.ts
  frontend/integration-tests/tests/kubevirt/models/kubevirtDetailView.ts
  frontend/integration-tests/tests/kubevirt/models/pod.ts
  frontend/integration-tests/tests/kubevirt/models/template.ts
  frontend/integration-tests/tests/kubevirt/models/virtualMachine.ts
  frontend/integration-tests/tests/kubevirt/models/virtualMachineInstance.ts
  frontend/integration-tests/tests/kubevirt/node.maintenance.scenario.ts
  frontend/integration-tests/tests/kubevirt/template.actions.scenario.ts
  frontend/integration-tests/tests/kubevirt/template.wizard.scenario.ts
  frontend/integration-tests/tests/kubevirt/utils/utils.ts
  frontend/integration-tests/tests/kubevirt/vm.actions.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.nic.binding.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.overview.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.wizard.scenario.ts
  frontend/integration-tests/tests/kubevirt/vm.yaml.scenario.ts
  frontend/integration-tests/tests/kubevirt/windows.scenario.ts
Labels: size/XL

#383 Added few more queries to utlization card
  frontend/public/kubevirt/components/dashboards/utils.js
  frontend/public/storage/components/storage-overview/storage-overview.jsx
Labels: size/M
